version: 0.0
os: linux
files:
  - source: target/bicicletario-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
